# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bw_boot <- function(x, h, g) {
    .Call('_baggingbwsel_bw_boot', PACKAGE = 'baggingbwsel', x, h, g)
}

Cbw_boot <- function(n, d, cnt, h, g) {
    .Call('_baggingbwsel_Cbw_boot', PACKAGE = 'baggingbwsel', n, d, cnt, h, g)
}

Cbw_ucv_nb <- function(x, h) {
    .Call('_baggingbwsel_Cbw_ucv_nb', PACKAGE = 'baggingbwsel', x, h)
}

Cbw_ucv <- function(n, d, cnt, h) {
    .Call('_baggingbwsel_Cbw_ucv', PACKAGE = 'baggingbwsel', n, d, cnt, h)
}

bw_den <- function(nbin, x) {
    .Call('_baggingbwsel_bw_den', PACKAGE = 'baggingbwsel', nbin, x)
}

bw_den_binned <- function(sx) {
    .Call('_baggingbwsel_bw_den_binned', PACKAGE = 'baggingbwsel', sx)
}

prnw <- function(x, y, h, x0) {
    .Call('_baggingbwsel_prnw', PACKAGE = 'baggingbwsel', x, y, h, x0)
}

nw_cv <- function(x, y, h) {
    .Call('_baggingbwsel_nw_cv', PACKAGE = 'baggingbwsel', x, y, h)
}

nw_cv_binning <- function(x, y, nb, d, h) {
    .Call('_baggingbwsel_nw_cv_binning', PACKAGE = 'baggingbwsel', x, y, nb, d, h)
}

new_nw_cv_binning <- function(x, y, ind, nb, d, h) {
    .Call('_baggingbwsel_new_nw_cv_binning', PACKAGE = 'baggingbwsel', x, y, ind, nb, d, h)
}

nw_binning <- function(k, x, y, nb, d, h) {
    .Call('_baggingbwsel_nw_binning', PACKAGE = 'baggingbwsel', k, x, y, nb, d, h)
}

